version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Jest Tests
          command: |
            npm install
            npm test
  build_and_push_image:
    machine: true
    steps:
      - run:
          name: Check directory
          command: |
            ls
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          dockerfile: Dockerfile
          path: .
          registry-id: AWS_ECR_REGISTRY_ID
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: eu-west-2
          repo: "es-22-23"
          tag: 'client_panel'
             
workflows:
  test-and-push:
    jobs:
      - test
      - build_and_push_image:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
